### ISSUE TITLE
Fatal error: strResult is not defined

### ISSUE THREAD

**Issue by nmccready** [nlaplante/grunt-git-log-json#6]
@nlaplante anyway you could dig into this? When the changelog gets generated for the website this error happens. TY.

**Comment by nlaplante** [comment]
I tested this on the develop branch of grunt-git-log-json, and it doesn't error out. Before I merge develop in master, could you please point npm to the develop branch of grunt-git-log-json? See [this page for an HOWTO](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies).

The dependency should be:
```
"grunt-git-log-json": "nlaplante/grunt-git-log-json#develop"
```

**Comment by nmccready** [comment]
On it; I'll test it.

**Comment by nmccready** [comment]
develop worked great thanks!
